version: "3.8"
services:
  front:
    build: .
    container_name: taskManager_1
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - /app/node_modules
